### ISSUE TITLE
Default value of "yes/no" field type

### ISSUE THREAD

**Issue by thehotery** [pluginsGLPI/fields#451]
I want to create new field that for computer item with type "Yes/no" and default value "**Yes**".  Some another issue have [link](https://github.com/pluginsGLPI/fields/blob/0.84/bugfixes/documentation/doc_plugin_fields.asciidoc) to (maybe outdated?) documentation.. it says

> \ 'Yes / No' type field
> The field is in the form of a drop-down list with 2 values: No / Yes. The default is 0 for No, 1 for Yes. The notion of mandatory / optional has no impact on this type of control. Because even without a default value, this field will take the value No (0), which is valid.
There's also another [documentation page](https://glpi-plugins.readthedocs.io/en/latest/fields/index.html) but it says nothing about how to specify default value of "Yes/No" type.

So i'm create a new field
![image](https://user-images.githubusercontent.com/62539068/127321114-acd3afd7-f573-4d9b-9696-3c229b077643.png)

But when i'm open any computer item, its shows like that ("No")
![image](https://user-images.githubusercontent.com/62539068/127321284-9750a03e-3166-4629-be89-82a9a9a10f64.png)

Yaml exports gives me following (looks like what i want)
```
container:
    6-Computer:
        id: 6
        name: comp_other_info
        itemtype: Computer
        type: dom
        subtype: null
        fields:
                                    HAVE MANY ITEMS THERE, REMOVED
            -
                id: 31
                label: NewYesNoField
                xml_node: NEWYESNOFIELDFIELD
                type: yesno
                ranking: 6
                default_value: '1'
                mandatory: 0
                possible_value:
                    -
                        id: 0
                        value: 'No'
                    -
                        id: 1
                        value: 'Yes'

```
